[package]
name = "league-motd"
version = "0.1.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]

[dependencies]
clap = "2.2.4"
encoding = "0.2"

[dependencies.redis]
version = "*"
features = ["unix_socket"]
